# Generated by Django 5.0.3 on 2024-03-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='description_cleaned',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='description_tokenized',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='embed_raw',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='description',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='descriptionWC',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='title',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
